### ISSUE TITLE
reverse pointers in multi set var

### ISSUE THREAD

**Issue by dobe** [simpl/ngx_devel_kit#3]
hi 
the example here https://github.com/simpl/ngx_devel_kit/blob/master/examples/http/set_var/ngx_http_set_var_examples_module.c#L72 states that v+1 should be a pointer to the next variable, which at least on macosx is not the case, actually the pointer v points to the last variable:

so it should mean:

v2 = v;
v = v2-1;

for the example to work.
ist this by intent?

regards, bernd

in the example

**Comment by ghost** [comment]
Hi Bernd,

This function uses ndk_set_var_multi_value, which passes a pointer to the first variable in a series.  

You can see from
https://github.com/simpl/ngx_devel_kit/blob/master/src/ndk_set_var.c#L180
that the 'multi' set_var funcs reduce the pointer by the 'size' given in the struct that is passed to it, and you can see from the ngx_http_var_set_concat2 struct that the 'size' is 2 - hence this pointer subtraction has already taken place before you get to the called function.

If the 'size' in the struct were '1', then the code you gave would work, but it isn't.

If you have actually tested the code and get a segfault or incorrect answer, then please let me know (but I'm pretty sure it's working correctly).

Regards,

Marcus.

**Comment by dobe** [comment]
thanks for the very fast reply!

with your hints i've found the problem, which was my fault. the size was right but i've used  NDK_SET_VAR_VALUE instead of NDK_SET_VAR_MULTI_VALUE, this was one spot i've missed when converting a single value to a multi value filter :(

thx again, bernd

**Comment by ghost** [comment]
No worries.  I guessed it was something like that.

Good luck with your module development!

Marcus.
