### ISSUE TITLE
ndk_conf_set_http_complex_value_slot() assignment issue.

### ISSUE THREAD

**Issue by mtourne** [simpl/ngx_devel_kit#4]
hi,
it's a minor detail, but looks like in ndk_conf_set_http_complex_value_slot() : 
cf->value = value[1] is not necessary, it seems like it will be overwritten by "value" in ngx_http_compile_complex_value() called by ndk_http_complex_value_compile() 
also ndk_http_complex_value_compile should be called with &value[1] rather than "value", otherwise the name of the directive ends up in the value field.

here is my proposed patch (btw, trailing whitespace in your code causes "blank line" diffs):

<pre>
 ngx_int_t
@@ -78,7 +78,7 @@ ndk_conf_set_http_complex_value_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *
     ngx_http_complex_value_t    *cv;
     ngx_str_t                   *value;
     ngx_conf_post_t             *post;
-
+
     cv = (ngx_http_complex_value_t *) (p + cmd->offset);

     if (cv->value.data) {
@@ -87,10 +87,9 @@ ndk_conf_set_http_complex_value_slot (ngx_conf_t *cf, ngx_command_t *cmd, void *

     value = cf->args->elts;

-    cv->value = value[1];
-
-    if (ndk_http_complex_value_compile (cf, cv, value))
+    if (ndk_http_complex_value_compile (cf, cv, &value[1])) {
         return  NGX_CONF_ERROR;
+    }

     if (cmd->post) {
         post = cmd->post;
</pre>

**Comment by ghost** [comment]
Yes,

You're right.  This was a function I wrote quite a while ago, but I don't think I use it directly, and clearly the odd bug slipped through the net.

Thanks for pointing it out.  I'll include it in the next release.  Let me know if you spot any other bugs.

Cheers,

Marcus.
