### ISSUE TITLE
can't install ndk.

### ISSUE THREAD

**Issue by nathan-zhu** [simpl/ngx_devel_kit#8]
Hi, i download it and use command line to install it.

brew install nginx-full --add-modul=xxxx/ngx_devel_kit/src

start nginx still get error like below
nginx: [emerg] unknown directive "set_by_lua"

how to do it, please help.thanks

**Comment by ghost** [comment]
The set_by_lua command is related to the Lua module, not NDK.  You need to add --add-module=xxx paths for both NDK and for Lua.  See the Lua notes for info on the ordering of modules when compiling (as it is usually important).
